export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

export const EMBED_LINK_REQUEST = 'EMBED_LINK_REQUEST'
export const EMBED_LINK_SUCCESS = 'EMBED_LINK_SUCCESS'
export const EMBED_LINK_FAIL = 'EMBED_LINK_FAIL'
