export const READING_CREATE_REQUEST = 'READING_CREATE_REQUEST'
export const READING_CREATE_SUCCESS = 'READING_CREATE_SUCCESS'
export const READING_CREATE_FAIL = 'READING_CREATE_FAIL'
export const READING_CREATE_RESET = 'READING_CREATE_RESET'

export const READING_UPDATE_REQUEST = 'READING_UPDATE_REQUEST'
export const READING_UPDATE_SUCCESS = 'READING_UPDATE_SUCCESS'
export const READING_UPDATE_FAIL = 'READING_UPDATE_FAIL'
export const READING_UPDATE_RESET = 'READING_UPDATE_RESET'

export const READING_LIST_REQUEST = 'READING_LIST_REQUEST'
export const READING_LIST_SUCCESS = 'READING_LIST_SUCCESS'
export const READING_LIST_FAIL = 'READING_LIST_FAIL'

export const READING_DETAILS_REQUEST = 'READING_DETAILS_REQUEST'
export const READING_DETAILS_SUCCESS = 'READING_DETAILS_SUCCESS'
export const READING_DETAILS_FAIL = 'READING_DETAILS_FAIL'

export const READING_DELETE_REQUEST = 'READING_DELETE_REQUEST'
export const READING_DELETE_SUCCESS = 'READING_DELETE_SUCCESS'
export const READING_DELETE_FAIL = 'READING_DELETE_FAIL'
