export const CREATE_SUNDAY_EMBED_LINK_REQUEST =
  'CREATE_SUNDAY_EMBED_LINK_REQUEST'
export const CREATE_SUNDAY_EMBED_LINK_SUCCESS =
  'CREATE_SUNDAY_EMBED_LINK_SUCCESS'
export const CREATE_SUNDAY_EMBED_LINK_FAIL = 'CREATE_SUNDAY_EMBED_LINK_FAIL'
export const CREATE_SUNDAY_EMBED_LINK_RESET = 'CREATE_SUNDAY_EMBED_LINK_RESET'

export const UPDATE_SUNDAY_EMBED_LINK_REQUEST =
  'UPDATE_SUNDAY_EMBED_LINK_REQUEST'
export const UPDATE_SUNDAY_EMBED_LINK_SUCCESS =
  'UPDATE_SUNDAY_EMBED_LINK_SUCCESS'
export const UPDATE_SUNDAY_EMBED_LINK_FAIL = 'UPDATE_SUNDAY_EMBED_LINK_FAIL'
export const UPDATE_SUNDAY_EMBED_LINK_RESET = 'UPDATE_SUNDAY_EMBED_LINK_RESET'

export const LIST_SUNDAY_EMBED_LINK_REQUEST = 'LIST_SUNDAY_EMBED_LINK_REQUEST'
export const LIST_SUNDAY_EMBED_LINK_SUCCESS = 'LIST_SUNDAY_EMBED_LINK_SUCCESS'
export const LIST_SUNDAY_EMBED_LINK_FAIL = 'LIST_SUNDAY_EMBED_LINK_FAIL'

export const GET_SUNDAY_EMBED_LINK_REQUEST = 'GET_SUNDAY_EMBED_LINK_REQUEST'
export const GET_SUNDAY_EMBED_LINK_SUCCESS = 'GET_SUNDAY_EMBED_LINK_SUCCESS'
export const GET_SUNDAY_EMBED_LINK_FAIL = 'GET_SUNDAY_EMBED_LINK_FAIL'

export const DELETE_SUNDAY_EMBED_LINK_REQUEST =
  'DELETE_SUNDAY_EMBED_LINK_REQUEST'
export const DELETE_SUNDAY_EMBED_LINK_SUCCESS =
  'DELETE_SUNDAY_EMBED_LINK_SUCCESS'
export const DELETE_SUNDAY_EMBED_LINK_FAIL = 'DELETE_SUNDAY_EMBED_LINK_FAIL'
