export const SUNDAY_CREATE_REQUEST = 'SUNDAY_CREATE_REQUEST'
export const SUNDAY_CREATE_SUCCESS = 'SUNDAY_CREATE_SUCCESS'
export const SUNDAY_CREATE_FAIL = 'SUNDAY_CREATE_FAIL'
export const SUNDAY_CREATE_RESET = 'SUNDAY_CREATE_RESET'

export const SUNDAY_UPDATE_REQUEST = 'SUNDAY_UPDATE_REQUEST'
export const SUNDAY_UPDATE_SUCCESS = 'SUNDAY_UPDATE_SUCCESS'
export const SUNDAY_UPDATE_FAIL = 'SUNDAY_UPDATE_FAIL'
export const SUNDAY_UPDATE_RESET = 'SUNDAY_UPDATE_RESET'

export const SUNDAY_LIST_REQUEST = 'SUNDAY_LIST_REQUEST'
export const SUNDAY_LIST_SUCCESS = 'SUNDAY_LIST_SUCCESS'
export const SUNDAY_LIST_FAIL = 'SUNDAY_LIST_FAIL'

export const SUNDAY_GET_REQUEST = 'SUNDAY_GET_REQUEST'
export const SUNDAY_GET_SUCCESS = 'SUNDAY_GET_SUCCESS'
export const SUNDAY_GET_FAIL = 'SUNDAY_GET_FAIL'

export const SUNDAY_DELETE_REQUEST = 'SUNDAY_DELETE_REQUEST'
export const SUNDAY_DELETE_SUCCESS = 'SUNDAY_DELETE_SUCCESS'
export const SUNDAY_DELETE_FAIL = 'SUNDAY_DELETE_FAIL'
