export const WED_CREATE_REQUEST = 'WED_CREATE_REQUEST'
export const WED_CREATE_SUCCESS = 'WED_CREATE_SUCCESS'
export const WED_CREATE_FAIL = 'WED_CREATE_FAIL'
export const WED_CREATE_RESET = 'WED_CREATE_RESET'

export const WED_UPDATE_REQUEST = 'WED_UPDATE_REQUEST'
export const WED_UPDATE_SUCCESS = 'WED_UPDATE_SUCCESS'
export const WED_UPDATE_FAIL = 'WED_UPDATE_FAIL'
export const WED_UPDATE_RESET = 'WED_UPDATE_RESET'

export const WED_LIST_REQUEST = 'WED_LIST_REQUEST'
export const WED_LIST_SUCCESS = 'WED_LIST_SUCCESS'
export const WED_LIST_FAIL = 'WED_LIST_FAIL'

export const WED_GET_REQUEST = 'WED_GET_REQUEST'
export const WED_GET_SUCCESS = 'WED_GET_SUCCESS'
export const WED_GET_FAIL = 'WED_GET_FAIL'

export const WED_DELETE_REQUEST = 'WED_DELETE_REQUEST'
export const WED_DELETE_SUCCESS = 'WED_DELETE_SUCCESS'
export const WED_DELETE_FAIL = 'WED_DELETE_FAIL'
