export const CREATE_WEDNESDAY_EMBED_LINK_REQUEST =
  'CREATE_WEDNESDAY_EMBED_LINK_REQUEST'
export const CREATE_WEDNESDAY_EMBED_LINK_SUCCESS =
  'CREATE_WEDNESDAY_EMBED_LINK_SUCCESS'
export const CREATE_WEDNESDAY_EMBED_LINK_FAIL =
  'CREATE_WEDNESDAY_EMBED_LINK_FAIL'
export const CREATE_WEDNESDAY_EMBED_LINK_RESET =
  'CREATE_WEDNESDAY_EMBED_LINK_RESET'

export const UPDATE_WEDNESDAY_EMBED_LINK_REQUEST =
  'UPDATE_WEDNESDAY_EMBED_LINK_REQUEST'
export const UPDATE_WEDNESDAY_EMBED_LINK_SUCCESS =
  'UPDATE_WEDNESDAY_EMBED_LINK_SUCCESS'
export const UPDATE_WEDNESDAY_EMBED_LINK_FAIL =
  'UPDATE_WEDNESDAY_EMBED_LINK_FAIL'
export const UPDATE_WEDNESDAY_EMBED_LINK_RESET =
  'UPDATE_WEDNESDAY_EMBED_LINK_RESET'

export const LIST_WEDNESDAY_EMBED_LINK_REQUEST =
  'LIST_WEDNESDAY_EMBED_LINK_REQUEST'
export const LIST_WEDNESDAY_EMBED_LINK_SUCCESS =
  'LIST_WEDNESDAY_EMBED_LINK_SUCCESS'
export const LIST_WEDNESDAY_EMBED_LINK_FAIL = 'LIST_WEDNESDAY_EMBED_LINK_FAIL'

export const GET_WEDNESDAY_EMBED_LINK_REQUEST =
  'GET_WEDNESDAY_EMBED_LINK_REQUEST'
export const GET_WEDNESDAY_EMBED_LINK_SUCCESS =
  'GET_WEDNESDAY_EMBED_LINK_SUCCESS'
export const GET_WEDNESDAY_EMBED_LINK_FAIL = 'GET_WEDNESDAY_EMBED_LINK_FAIL'

export const DELETE_WEDNESDAY_EMBED_LINK_REQUEST =
  'DELETE_WEDNESDAY_EMBED_LINK_REQUEST'
export const DELETE_WEDNESDAY_EMBED_LINK_SUCCESS =
  'DELETE_WEDNESDAY_EMBED_LINK_SUCCESS'
export const DELETE_WEDNESDAY_EMBED_LINK_FAIL =
  'DELETE_WEDNESDAY_EMBED_LINK_FAIL'
